state_regions = {
    'AK': 'O',
    'AL': 'S',
    'AR': 'S',
    'AS': 'O',
    'AZ': 'W',
    'CA': 'W',
    'CO': 'W',
    'CT': 'N',
    'DC': 'N',
    'DE': 'N',
    'FL': 'S',
    'GA': 'S',
    'GU': 'O',
    'HI': 'O',
    'IA': 'M',
    'ID': 'W',
    'IL': 'M',
    'IN': 'M',
    'KS': 'M',
    'KY': 'S',
    'LA': 'S',
    'MA': 'N',
    'MD': 'N',
    'ME': 'N',
    'MI': 'W',
    'MN': 'M',
    'MO': 'M',
    'MP': 'O',
    'MS': 'S',
    'MT': 'W',
    'NA': 'O',
    'NC': 'S',
    'ND': 'M',
    'NE': 'W',
    'NH': 'N',
    'NJ': 'N',
    'NM': 'W',
    'NV': 'W',
    'NY': 'N',
    'OH': 'M',
    'OK': 'S',
    'OR': 'W',
    'PA': 'N',
    'PR': 'O',
    'RI': 'N',
    'SC': 'S',
    'SD': 'M',
    'TN': 'S',
    'TX': 'S',
    'UT': 'W',
    'VA': 'S',
    'VI': 'O',
    'VT': 'N',
    'WA': 'W',
    'WI': 'M',
    'WV': 'S',
    'WY': 'W'
}

abbreviations = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

region_abbv = {
    'N': 'North East',
    'W': 'West',
    'M': 'Mid West',
    'S': 'South',
    'O': 'Other',
    'I': 'International',
}